SELECT
P.PRODUCT_CODE, S.SALES_AMOUNT * P.PRICE AS SALES
FROM PRODUCT AS P
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
      FROM OFFLINE_SALE GROUP BY PRODUCT_ID) AS S
      ON P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC


--해당 쿼리도 가능--
SELECT
P.PRODUCT_CODE, SUM(S.SALES_AMOUNT * P.PRICE) AS SALES
FROM PRODUCT AS P
JOIN OFFLINE_SALE AS S
ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY S.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC