-- 코드를 입력하세요
SELECT 
HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE,
date_format(END_DATE,'%Y-%m-%d') AS END_DATE,
CASE WHEN DATEDIFF(END_DATE, START_DATE) >= 29 -- 하;;
THEN '장기 대여' ELSE '단기 대여' END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE LIKE '2022-09-%'
ORDER BY HISTORY_ID DESC

-- TIMESTAMPDIFF(DAY, END_DATE, START_DATE)도 가능
-- 해당 함수는 SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, QUARTER, YEAR도 계산가능