-- 코드를 입력하세요
SELECT
C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE * 30 * (1 - 0.01 * D.DISCOUNT_RATE)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN (SELECT CAR_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
      WHERE DURATION_TYPE = '30일 이상') AS D
ON D.CAR_TYPE = C.CAR_TYPE
WHERE FLOOR(C.DAILY_FEE * 30 * (1 - 0.01 * D.DISCOUNT_RATE)) >= 500000 
AND FLOOR(C.DAILY_FEE * 30 * (1 - 0.01 * D.DISCOUNT_RATE)) < 2000000 
AND (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
AND C.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE '2022-11-1' <= END_DATE AND '2022-11-30' >= START_DATE) 
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
           