SELECT 
ITEM_ID, ITEM_NAME, RARITY
FROM
ITEM_INFO
WHERE ITEM_ID IN 
(SELECT 
 I.ITEM_ID 
 FROM ITEM_TREE AS T RIGHT OUTER JOIN ITEM_INFO AS I
 ON T.PARENT_ITEM_ID = I.ITEM_ID
 WHERE T.ITEM_ID IS NULL) 
 ORDER BY ITEM_ID DESC