SELECT
HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) <= 19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR ASC


-- HAVING HOUR >= 9 and HOUR <= 19 도 가능 
-- 보통 GROUP BY + HAVING을 쓴다.