-- 코드를 입력하세요
SELECT 
BOARD.TITLE,
BOARD.BOARD_ID,
REPLY.REPLY_ID,
REPLY.WRITER_ID,
REPLY.CONTENTS,
date_format(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS BOARD
INNER JOIN USED_GOODS_REPLY AS REPLY
ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE BOARD.CREATED_DATE like '2022-10%' -- 게시글이 10월에 작성된....
ORDER BY REPLY.CREATED_DATE ASC, BOARD.TITLE ASC

--MONTH(DATE) = 10 and YEAR(DATE) = 2022도 가능