SELECT
OS.YEAR, OS.MONTH,
COUNT(OS.USER_ID) AS PUCHASED_USERS,
ROUND(COUNT(OS.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) ="2021"),1) AS PURHCASED_RATIO
FROM 
(SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
 FROM ONLINE_SALE 
 WHERE USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) ="2021") 
 GROUP BY USER_ID,YEAR(SALES_DATE),MONTH(SALES_DATE)) AS OS
GROUP BY OS.YEAR, OS.MONTH
ORDER BY YEAR, MONTH

-- DISTINCT 사용
SELECT
OS.YEAR, OS.MONTH,
COUNT(DISTINCT(OS.USER_ID)) AS PUCHASED_USERS,
ROUND(COUNT(DISTINCT(OS.USER_ID))/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) ="2021"),1) AS PURHCASED_RATIO
FROM 
(SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
 FROM ONLINE_SALE 
 WHERE USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) ="2021")) AS OS
GROUP BY OS.YEAR, OS.MONTH
ORDER BY YEAR, MONTH