SELECT 
T.ID, 
CASE 
WHEN T.SIZE = 1 THEN "CRITICAL"
WHEN T.SIZE = 2 THEN "HIGH"
WHEN T.SIZE = 3 THEN "MEDIUM"
ELSE "LOW" END COLONY_NAME
FROM (SELECT ID, 
      NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE
      FROM ECOLI_DATA) AS T
ORDER BY T.ID